### ISSUE TITLE
Use module bundler

### ISSUE THREAD

**Issue by aecostas** [cassproject/cass-npm#2]
It would be great to use a tool to pack all the files or the project, like [webpack](https://webpack.js.org/). Current implementation based on `eval(load.call(this,"<filename>")+"");` have some issues:

* it is difficult to debug the application since all the errors are triggered in `index.js` instead of the source file:

```
(node:14572) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toPem' of null
    at EcEncryptedValue.prototype.addReader (eval at <anonymous> (/home/aestevez/devel/cass-client/node_modules/cassproject/index.js:59:1), <anonymous>:671:29)
    at Function.constructor.encryptValue (eval at <anonymous> (/home/aestevez/devel/cass-client/node_modules/cassproject/index.js:59:1), <anonymous>:217:19)
    at EcAssertion.prototype.setSubject (eval at <anonymous> (/home/aestevez/devel/cass-client/node_modules/cassproject/index.js:61:1), <anonymous>:341:41)
```
* dangerous: https://stackoverflow.com/questions/197769/when-is-javascripts-eval-not-evil

**Comment by Lomilar** [comment]
Oh, I definitely agree about eval, and that our solution isn't optimal.

The reason it is so awkward is that we are going from Javascript from Java using a transpiler that targets browsers, and doesn't know how to output or export Require based modules.

Typically, we first publish all of our js libraries in jars using Maven Central (for code signing reasons, mostly) and then pull down and package our software via a pom.xml

We have examples of projects packaging and minifying (not using the npm package) using Google Closure via a maven plugin.
https://github.com/cassproject/cass-editor/blob/master/pom.xml

I think we're including require.js but not using it at the moment, as we browserify any modules that come from npm.

I have thought about looking into code generating index.js files for each of our sublibraries and then cross-publishing to both Maven Central and NPM, so this is a stopgap until we get some way for our libraries to compile into Require modules. Unfortunately, this tech stack isn't my area of expertise.

Do you have advice or links about how to turn browser-ready code into Require modules -- preferably programmatically? I'd love to have a better solution.

**Comment by Lomilar** [comment]
This is now addressed. We have a script that code-generates the output.js that makes up the bulk of the node module.
