### ISSUE TITLE
EcFramework.search doesn't return requested size

### ISSUE THREAD

**Issue by veden** [cassproject/cass-npm#8]
If the elastic instance has 5 records and the first two are private and I don't have access to them.

When requesting a search result 
```
EcFramework.search(repo, "", (response) => { console.log(response)},(e) => {console.log(e),{size:3, start:0})
```

The records returned doesn't account for records that are filtered due to a lack of access.

So if the the first 2 records are private and I have access to the third, I will get one result instead of three.

**Comment by Lomilar** [comment]
Done.
